### PR TITLE
implement a GenStage producer for in-order subscriptions

### PR DESCRIPTION
**Pull request by the-mikedavis**
tries to emulate Volley.LinearSubscription as closely as possible

no real docs to speak of yet

### CODE REVIEW

**Comment by the-mikedavis** [comment]
eventually I'd like to add some tests that try stuff out like ~emulating tcp_closed~ (:heavy_check_mark:) and raising in the consumer's body

**Comment by the-mikedavis** [comment]
this linear subscriber implementation is kinda fun because it needs to act as a buffer against the extreme reading subscription and as a buffer against the demand of the consumer

two way buffer!

**Comment by tonyvanriet** [comment]
so, it doesn't ever push back to `extreme`, right? just holds everything in the LinearSubscription state.

trying to piece together the history (again), and then compare that to this change...

long ago we had performance problems when subscribing to a large stream where we had to catch up.
that was because extreme was filling up our mailbox asynchronously, much faster than we were processing them, and big mailboxes hurt the whole app.
then there was a change where extreme was giving us messages synchronously so mailbox didn't get full.
I just don't remember where the messages were getting buffered at that point. were they just piling up in some extreme process state, or did it actually use TCP backpressure to the eventstore?
I don't recall ever looking into that... it just worked.

so we're either moving the buffering from some extreme client process to this LinearSubscription GenServer :+1: 
or we're moving from eventstore backpressure to buffering in this LinearSubscription GenServer :-1:

**Review by tonyvanriet — APPROVED** [review]

**Comment by the-mikedavis** [comment]
lemme whip out the :neckbeard: for

> TCP backpressure

sadly no way to do backpressure on a whole TCP connection and also do multiplexing which the eventstore connection does (although you could do this with HTTP/2 which is technically TCP)

this linear subscriber takes advantage of extreme's reading subscription which performs reads as a catch-up mechanism and then subscribes to the end of the stream, so really this GenStage isn't itself providing any backpressure: it's still extreme.

this genstage has a `handle_call/3` implementation which enforces this backpressure. in fact it's kinda bad performance-wise because we're only actually buffering 1 event at a time and only taking multiple events when the consumer's demand ask is > 1

**Comment by tonyvanriet** [comment]
> sadly no way to do backpressure on a whole TCP connection and also do multiplexing which the eventstore connection does (although you could do this with HTTP/2 which is technically TCP)

you're saying there's no way extreme couldn't have been doing TCP backpressure because it's client connection was being shared by multiple subscribers and aggregate repos in those old apps?

> this linear subscriber takes advantage of extreme's reading subscription which performs reads as a catch-up mechanism and then subscribes to the end of the stream, so really this GenStage isn't itself providing any backpressure: it's still extreme.

this is the same extreme subscription mechanism our ExStream subscriber was always using, right? so, it was neither of the things I mentioned. the events were not piling up in extreme because extreme was doing a catch-up read at its own pace.

> this genstage has a handle_call/3 implementation which enforces this backpressure. in fact it's kinda bad performance-wise because we're only actually buffering 1 event at a time and only taking multiple events when the consumer's demand ask is > 1

hmm, not understanding this. it looks to me that while the consumer's demand is 0, this process will buffer up in its genserver state as fast as it can. it's only *giving* multiple events when the consumer's demand is > 1, but it's taking them as fast as it can put them in state. no?

**Comment by tonyvanriet** [comment]
oh, I missed the `:noreply`

``` elixir
  def handle_call({:on_event, event}, from, state) do
    case state.demand do
      0 ->
        {:noreply, [], put_in(state.buffer, {event, from})}
```

when demand is 0, buffer and don't reply, which blocks extreme, same as we do today.

so, now as I understand it, this doesn't change the external upstream behavior of our subscriptions, but it allows the consumer to provide a max demand > 1, while today's solution is effectively max demand = 1.

now do I have it?

**Pull request merged**
