### PR TITLE
Bump deps including extreme

### PR DESCRIPTION
**Pull request by svrdlans**
fixes [issue](https://github.com/NFIBrokerage/agora/issues/1118) that occurred in `agora` caused by a bug in `extreme` library addressed with [this PR](https://github.com/exponentially/extreme/pull/78)

### CODE REVIEW

**Comment by tonyvanriet** [comment]
I think we need to change the extreme dep constraint in mix.exs to ensure host applications use the fixed version. 

maybe `~> 1.0 and >= v1.0.5` ?

**Review by tonyvanriet — CHANGES_REQUESTED** [review]
dep constraint

**Comment by svrdlans** [comment]
shouldn't `>= 1.0.5` suffice?

**Comment by svrdlans** [comment]
although I do believe bumping kelvin in harness libs and (unharnessed) apps will give us the desired effect

**Comment by tonyvanriet** [comment]
yes, just running deps.update in the host app needs to be done and will update extreme, I think it's important for the dependency tree to actually try to prevent people from using < 1.0.5.

if it's only `>= 1.0.5`, then it would allow `deps.update` to extreme 2.x even though that would include breaking changes, in theory. I think the `~> 1.0` is important for ensuring any move to 2.x is done deliberately.

all ears for arguments against this, but that's my take.

**Comment by svrdlans** [comment]
ah, good point, I was thinking 2.0 is so far away from us (if it comes at all), that we don't need to worry at all

but definitely makes sense to not let it be accidental

**Review by tonyvanriet — APPROVED** [review]

**Pull request merged**
